//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 08/26/2015 16:23:09
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Microsoft.IoT.DeviceHelpers
{
    using Windows.ApplicationModel.Resources;
    
    
    internal partial class Strings
    {
        
        private static ResourceLoader resourceLoader;
        
        static Strings()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Strings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Strings");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Strings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The device '{0}' could not be found"
        /// </summary>
        public static string DeviceNotFound
        {
            get
            {
                return resourceLoader.GetString("DeviceNotFound");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The requested IO change is not supported in the current state"
        /// </summary>
        public static string IOChangeState
        {
            get
            {
                return resourceLoader.GetString("IOChangeState");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The required IO device property '{0}' has not been assigned"
        /// </summary>
        public static string MissingRequiredIO
        {
            get
            {
                return resourceLoader.GetString("MissingRequiredIO");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The element {'0'} is missing from the '{1}' template"
        /// </summary>
        public static string MissingTemplateElement
        {
            get
            {
                return resourceLoader.GetString("MissingTemplateElement");
            }
        }
    }
}
